### ISSUE TITLE
Is segmentMedian a median filter?

### ISSUE THREAD

**Issue by ahundt** [HiKapok/KaggleCompetitions#1]
Is it the same as a median filter?
http://scikit-image.org/docs/dev/_images/sphx_glr_plot_rank_filters_002.png

**Comment by HiKapok** [comment]
segment Median is something like segment_mean in tensorflow

**Comment by ahundt** [comment]
ah so more for running median on contiguously labeled data rather than a type of median convolution. Thanks!
